version: "3.7"

services:
  db:
    build: ./db
    container_name: db_postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: devcamp_2022
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:5.0.7
    container_name: redis
    restart: always
    volumes:
      - ./data/redis:/data
    ports:
      - "6379:6379"