{
 "title": "HTTP Overview",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "path", "label": "Endpoint", "query": { "query": "label_values(path)" } }
  ]
 },
 "panels": [
  {
   "title": "Incoming Requests",
   "type": "table-old",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(http_requests_total[$__range])) by (path) > 0"
    },
    {
     "expr": "sum(increase(http_response_time_seconds_sum[$__rate_interval])) by (path) / sum(increase(http_requests_total[$__rate_interval])) by (path)"
    },
    {
     "expr": "(sum(increase(response_status{status!~\"(1|2|3)\\\\d\\\\d\"}[$__rate_interval])) by (path) \n/ sum(increase(http_requests_total[$__rate_interval])) by (path)) >= 0\nor (sum(increase(http_requests_total[$__rate_interval])) by (path) > 0) * 0"
    }
   ]
  },
  {
   "title": "Overall",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "repeat": "service",
   "targets": [
    {}
   ]
  },
  {
   "title": "Request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(increase(http_requests_total[$__rate_interval])) by (path)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Incoming Avg. Response Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 10, "y": 10 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "(sum(increase(http_response_time_seconds_sum[$__rate_interval])) by (path)\n/ sum(increase(http_requests_total[$__rate_interval])) by (path)) >= 0",
     "legendFormat": "{{http_path}}"
    }
   ]
  },
  {
   "title": "In Req / Sec",
   "type": "stat",
   "description": "Incoming HTTP Requests per second for the selected endpoints and applications",
   "gridPos": { "h": 8, "w": 3, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "In Error Rate",
   "type": "stat",
   "description": "The error rate of incoming http requests for the selected endpoints and applications",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(increase(response_status{status!~\"(1|2|3)\\\\d\\\\d\"}[$__rate_interval]))  \n/ sum(increase(http_requests_total[$__rate_interval])) ) >= 0\nor (sum(increase(http_requests_total[$__rate_interval]))  > 0) * 0"
    }
   ]
  }
 ]
}